name: salmon
channels:
  - conda-forge
dependencies:
  - python=3.11
  - ipython
  - ipykernel
  - ipywidgets
  - pandas
  - matplotlib
  - seaborn
  - jupyter
  - jupyterlab
  - git
  - pip
  - pip:
    - gdown
    - pycaret
    - shap
    - catboost
    - xgboost
    - pyreadstat
    - statsmodels
    - pingouin
    - voila
    - scikit-learn
    - scikit-image
    - itkwidgets
    - imageio
    - tiffile
    - nilearn
    - networkx
    - openpyxl
    - pygraphviz
    - pydot
    - python-louvain
    - streamlit
    - sympy
    - mesa     # library specifically designed for agent-based modeling (ABM)

    

## Configure the Conda-environment salmon for data analysis, computational imaging and modeling (only once):
# conda env create -f environment.yml

## To make a salmon kernel (optional):
# python -m ipykernel install --user --name salmon --display-name "salmon"

## To activate the salmon conda environment:
# conda activate salmon

## To update the salmon conda environment:
# conda env update -f environment.yml

## To remove and reinstall the salmon environment (if installation problems):
# conda deactivate
# conda env remove -n salmon
# conda env create -f environment.yml
